#!/usr/bin/env bash

function separator() {
    local MSG=${1:-" "}
    echo " "
    echo "$MSG"
}

separator "JS environment setup"
sudo apt update && sudo apt upgrade

# Install NVM, Node & NPM
touch ~/.bash_profile
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
source ~/.nvm/nvm.sh && nvm install node && nvm use node 
nvm --version && node --version && npm --version

separator "JS setup complete"