#!/usr/bin/env bash

function separator() {
    local MSG=${1:-" "}
    echo " "
    echo "$MSG"
}


separator "Beginning PHP setup"
sudo apt update && sudo apt upgrade


# Install PHP
separator "Installing PHP:"
sudo apt install php
sudo apt install php8.2-xml
sudo apt install php-curl
sudo apt install php-sqlite3
sudo apt install php-gd
separator "PHP version:"
php --version


# Install composer
separator "Installing composer:"
sudo apt install composer
separator "Composer version:"
composer


# Install DDEV
separator "Installing DDEV:"
curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null
sudo apt update && sudo apt install -y ddev
separator "DDEV version:"
ddev --version


separator "PHP setup complete"