#!/usr/bin/env bash

GIT_EMAIL="88102362+marvinobig@users.noreply.github.com"
GIT_USERNAME="marvinobig"
GIT_BRANCH_NAME="main"
PARENT_DIR="repos"


function separator() {
    local MSG=${1:-" "}
    echo " "
    echo "$MSG"
}


separator "Beginning environment setup"
sudo apt update && sudo apt upgrade


# Install Git
separator "Installing Git:"
sudo apt-get install git
git --version 


# Configure GIT
separator "Configuring GIT:"
git config --global credential.helper store
git config --global user.name "$GIT_USERNAME"
git config --global user.email "$GIT_EMAIL"
git config --global init.defaultBranch "$GIT_BRANCH_NAME" 
git config --global core.editor "$GIT_EDITOR"
separator "GIT is configured:"
git config --global --list


# Setup Github SSH keygen
separator "Setup Github SSH keygen:"
ssh-keygen -t ed25519 -C "$GIT_EMAIL"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519


# Setup Github SSH keygen
separator "Installing zsh & oh-my-zsh:"
sudo apt-get install -y zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# change ZSH_THEME by adding "powerlevel10k/powerlevel10k" in .zhrc
# in .p10k.zsh file you can configure the theme


# Create Workspace
separator "Creating Parent Workspace:"
mkdir "../../$PARENT_DIR" && cd $PARENT_DIR


# Install Nerd Fonts
separator "Installing nerd fonts:"
git clone https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts
bash install.sh Hack


separator "System setup complete"
