#!/usr/bin/env bash

function separator() {
    local MSG=${1:-" "}
    echo " "
    echo "$MSG"
}


separator "Docker environment setup"
sudo apt update && sudo apt upgrade


#Install Docker
separator "Installing Docker:"
sudo apt update
sudo apt install ca-certificates curl gnupg lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io
sudo docker run hello-world
sudo groupadd docker
sudo usermod -aG docker ${USER}
su - ${USER}
groups
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
sudo apt install docker-compose-plugin
separator "Docker version:"
docker --version


separator "Docker setup complete"